-- Generated by scripts/generate-seed.mjs from src/data/fallback.js. Do not edit by hand.
-- Placeholder text starts with "[Placeholder]". Replace it from /admin.

truncate public.skills, public.experience, public.education, public.projects;
delete from public.profile;

insert into public.profile (id, full_name, eyebrow, tagline, intro, about_heading, about_body, hero_image_url, resume_url, email, phone, show_phone, github_url, linkedin_url, contact_blurb, stats) values
  (1, 'Archit Jain', 'Software Developer', 'I build apps for web and mobile.', '[Placeholder] A two-line intro about what you build and the kind of work you are looking for.', 'I''m passionate about building useful software', 'I''m an Information Technology student who loves turning ideas into real products. I''m especially interested in Artificial Intelligence and Machine Learning, and I want to bring them into apps I build for Android, Windows and the web. I also work as a freelance developer.

Right now I''m learning cross-platform development with Flutter. I''m always happy to collaborate on challenging projects built with the latest technology, so feel free to reach out by email or on LinkedIn.', '/seed/archit.jpg', '/seed/resume.pdf', 'architjain2005@gmail.com', '+91 7710990629', true, 'https://github.com/Archit-Jain05', 'https://www.linkedin.com/in/archit-jain-6021711aa', 'I''m always open to discussing new projects, freelance work and opportunities. Let''s build something great together!', '[{"value":"4+","label":"Years building","icon":"calendar"},{"value":"3","label":"Roles","icon":"briefcase"},{"value":"4+","label":"Projects","icon":"code"},{"value":"9.18","label":"CGPA","icon":"graduation"}]'::jsonb);

insert into public.skills (name, icon, percent, show_in_hero, sort_order) values
  ('HTML', 'SiHtml5', 80, true, 1),
  ('CSS', 'SiCss', 80, true, 2),
  ('JavaScript', 'SiJavascript', 80, true, 3),
  ('React', 'SiReact', 80, true, 4),
  ('Next.js', 'SiNextdotjs', 80, true, 5),
  ('TypeScript', 'SiTypescript', 80, true, 6),
  ('Flutter', 'SiFlutter', 80, false, 7),
  ('Shopify', 'SiShopify', 80, false, 8),
  ('Git', 'SiGit', 80, false, 9);

insert into public.experience (company, role, logo_url, start_date, end_date, description, website_url, sort_order) values
  ('ZootechX', 'Software Developer', '/seed/zootechx.png', '2026-08-01', null, 'Working as a software developer intern. My day-to-day ranges from writing code to coordinating with clients directly to understand their requirements and serve them better.', 'https://www.zootechx.com/', 1),
  ('Hophead.co', 'Web Developer Intern', '/seed/hophead.jpg', '2023-08-01', '2024-08-01', 'Built and maintained the brand''s e-commerce websites with Shopify and React.js, using creative UI/UX to bring in and keep online shoppers.', 'https://hophead.co.in/', 2),
  ('Dcyber Techlabs Pvt. Ltd', 'Web Developer Intern', '/seed/dcyber.png', '2022-08-01', '2022-09-01', 'Developed a website for the DCYBER Africa region using React.js.', 'https://dcyber.in/', 3);

insert into public.education (institution, course, logo_url, score, start_year, end_year, description, highlights, sort_order) values
  ('SVKM''s Dwarkadas J. Sanghvi College of Engineering', 'Bachelor of Technology', '/seed/djsce.jpg', '9.18 / 10 CGPA', 2024, 2027, null, array[]::text[], 1),
  ('SVKM''s Shri Bhagubhai Mafatlal Polytechnic', 'Diploma in Information Technology', '/seed/sbmp.jpg', '89.0%', 2021, 2024, null, array[]::text[], 2),
  ('Utpal Sanghvi Global School', 'X Standard IGCSE', '/seed/utpal.avif', '93.5%', 2011, 2021, null, array[]::text[], 3);

insert into public.projects (title, description, image_url, tech, github_url, live_url, sort_order) values
  ('ASMAAN', 'Immersive 3D Shopify storefront for India''s first botanical focus drink.', '/placeholder-project.svg', array['Shopify', 'Liquid', 'JavaScript']::text[], 'https://github.com/Archit-Jain05/drinkasmaan', 'https://xhp0ym-sn.myshopify.com/?pb=0', 1),
  ('MoneyMind', 'Flutter app for tracking expenses, scanning bills and creating invoices.', '/placeholder-project.svg', array['Flutter', 'Dart']::text[], 'https://github.com/Archit-Jain05/MoneyMind', null, 2),
  ('Velora', '[Placeholder] One-line description of Velora.', '/placeholder-project.svg', array['Next.js', 'TypeScript']::text[], 'https://github.com/Archit-Jain05/Velora', 'https://velora-ashen-psi.vercel.app', 3),
  ('bb3', '[Placeholder] One-line description of bb3.', '/placeholder-project.svg', array['Next.js', 'TypeScript']::text[], 'https://github.com/Archit-Jain05/bb3', 'https://bb3-teal.vercel.app', 4);
