// Generates supabase/seed.sql from src/data/fallback.js so both stay in sync.
// Usage: npm run seed:generate
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { fallbackContent } from "../src/data/fallback.js";

const lit = (value) => {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (Array.isArray(value)) return `array[${value.map(lit).join(", ")}]::text[]`;
  return `'${String(value).replace(/'/g, "''")}'`;
};

function insert(table, rows, columns) {
  const values = rows
    .map((row) => `  (${columns.map((c) => lit(row[c])).join(", ")})`)
    .join(",\n");
  return `insert into public.${table} (${columns.join(", ")}) values\n${values};\n`;
}

const { profile, skills, experience, education, projects } = fallbackContent;

const profileColumns = Object.keys(profile).filter((c) => c !== "stats");
const sql = `-- Generated by scripts/generate-seed.mjs from src/data/fallback.js. Do not edit by hand.
-- Placeholder text starts with "[Placeholder]". Replace it from /admin.

truncate public.skills, public.experience, public.education, public.projects;
delete from public.profile;

insert into public.profile (id, ${profileColumns.join(", ")}, stats) values
  (1, ${profileColumns.map((c) => lit(profile[c])).join(", ")}, ${lit(JSON.stringify(profile.stats))}::jsonb);

${insert("skills", skills, ["name", "icon", "percent", "show_in_hero", "sort_order"])}
${insert("experience", experience, ["company", "role", "logo_url", "start_date", "end_date", "description", "website_url", "sort_order"])}
${insert("education", education, ["institution", "course", "logo_url", "score", "start_year", "end_year", "sort_order"])}
${insert("projects", projects, ["title", "description", "image_url", "tech", "github_url", "live_url", "sort_order"])}`;

const out = fileURLToPath(new URL("../supabase/seed.sql", import.meta.url));
writeFileSync(out, sql);
console.log(`Wrote ${out}`);
